Clarify new unhollower assembly destination for MelonLoader versions over 0.6.0
LavaGang/MelonWiki pull request #86
Opened 2024-10-08 02:14 UTC by gl1tch638

Update quickstart.md

2024-10-08 02:58 UTC, loukylor requested changes

2024-10-09 00:53 UTC, gl1tch638 commented on docs/modders/quickstart.md
>  For games using the IL2CPP runtime, all the game/Unity assemblies can be found in `[Game Directory]\MelonLoader\Managed\` (make sure you have ran the game with MelonLoader at least once!).
Ok I edited it in my repo
If i messed it up please notify, this is a first for me

2024-10-09 00:54 UTC, gl1tch638 reviewed
Included line break tag as requested :)

2024-10-10 09:58 UTC, loukylor commented on docs/modders/quickstart.md
>  For games using the IL2CPP runtime, all the game/Unity assemblies can be found in `[Game Directory]\MelonLoader\Managed\` (make sure you have ran the game with MelonLoader at least once!).
I meant to add the tag to the line above the line you added. Make sure to remove the tag from your line. Also clarify that your line is only referring to Il2Cpp games.

2024-10-10 20:57 UTC, gl1tch638 commented on docs/modders/quickstart.md
>  For games using the IL2CPP runtime, all the game/Unity assemblies can be found in `[Game Directory]\MelonLoader\Managed\` (make sure you have ran the game with MelonLoader at least once!).
Ok, i made the changes

2024-10-11 21:50 UTC, loukylor commented
Awesome thank you!

2024-10-11 21:50 UTC, merged